# Generated by Django 3.1.5 on 2021-01-26 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('LRN', models.CharField(max_length=100, unique=True)),
                ('Status', models.BooleanField(default=False, verbose_name='Block Access')),
                ('Section', models.CharField(choices=[('7 Rizal', '7 Rizal'), ('7 Bonifacio', '7 Bonifacio'), ('7 Del Pilar', '7 Del Pilar'), ('8 Nakpil', '8 Nakpil'), ('8 Bernal', '8 Bernal'), ('8 Joaquin', '8 Joaquin'), ('9 Shakespeare', '9 Shakespeare'), ('9 Dickens', '9 Dickens'), ('9 Twain', '9 Twain'), ('10 Einstein', '10 Einstein'), ('10 Franklin', '10 Franklin'), ('10 Newton', '10 Newton'), ('11 ABM', '11 ABM'), ('11 GAS/HUMSS', '11 GAS/HUMSS'), ('11 STEM', '11 STEM'), ('12 ABM', '12 ABM'), ('12 GAS/HUMSS', '12 GAS/HUMSS'), ('12 STEM', '12 STEM')], max_length=100)),
                ('Quarter', models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('1', 'Third Quarter'), ('1', 'Fourth Quarter')], max_length=100, verbose_name='What Quarter ?')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('LRN', models.CharField(max_length=100, unique=True)),
                ('Status', models.BooleanField(default=False, verbose_name='Block Access')),
                ('Section', models.CharField(choices=[('11 ABM', '11 ABM'), ('11 GAS/HUMSS', '11 GAS/HUMSS'), ('11 STEM', '11 STEM'), ('12 ABM', '12 ABM'), ('12 GAS/HUMSS', '12 GAS/HUMSS'), ('12 STEM', '12 STEM')], max_length=100)),
                ('Quarter', models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('1', 'Third Quarter'), ('1', 'Fourth Quarter')], max_length=100, verbose_name='What Quarter ?')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False, verbose_name='Block Access')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirdgrade', to='api.juniorhigh')),
            ],
        ),
        migrations.CreateModel(
            name='SHSecondQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondgrade', to='api.seniorhigh')),
            ],
        ),
        migrations.CreateModel(
            name='SHFirstQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstgrade', to='api.seniorhigh')),
            ],
        ),
        migrations.CreateModel(
            name='SecondQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondgrade', to='api.juniorhigh')),
            ],
        ),
        migrations.CreateModel(
            name='FourthQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourthgrade', to='api.juniorhigh')),
            ],
        ),
        migrations.CreateModel(
            name='FirstQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstgrade', to='api.juniorhigh')),
            ],
        ),
    ]
