# Generated by Django 2.2.12 on 2021-11-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210126_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniorhigh',
            name='Teacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
