# Generated by Django 2.2.12 on 2021-11-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211103_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorhigh',
            name='Teacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
